# Generated by Django 5.2.6 on 2025-09-14 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Required. 30 characters or fewer. Letters, numbers, dots, hyphens, and underscores only.",
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username can only contain letters, numbers, dots, hyphens, and underscores.",
                        regex="^[a-zA-Z0-9._-]+$",
                    )
                ],
            ),
        ),
    ]
