version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - DJANGO_SETTINGS_MODULE=infikar.settings
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=mysql://infikar:infikar123@mysql:3306/infikar
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - redis
      - mysql
    networks:
      - infikar-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - infikar-network
    command: redis-server --appendonly yes

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=infikar
      - MYSQL_USER=infikar
      - MYSQL_PASSWORD=infikar123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - infikar-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  redis-data:
  mysql-data:

networks:
  infikar-network:
    driver: bridge
