# Generated by Django 5.2.6 on 2025-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
