# Generated by Django 5.2.6 on 2025-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cards/card_images/"
            ),
        ),
    ]
