# Generated by Django 5.2.6 on 2025-09-13 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("font_family", models.CharField(default="Inter", max_length=100)),
                ("font_weights", models.JSONField(default=list)),
                ("color_scheme", models.JSONField(default=dict)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="templates/"),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/previews/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("link", "Link Collection"),
                            ("about", "About"),
                            ("recommendation", "Recommendation/Top Picks"),
                            ("splash", "Splash"),
                            ("youtube", "YouTube Channel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_draft", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("custom_font_family", models.CharField(blank=True, max_length=100)),
                ("custom_font_weight", models.CharField(blank=True, max_length=20)),
                (
                    "custom_font_size",
                    models.PositiveIntegerField(
                        default=16,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(72),
                        ],
                    ),
                ),
                (
                    "custom_text_transform",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                            ("capitalize", "Capitalize"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "custom_background_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="cards.cardtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("user", "slug")},
            },
        ),
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cards/images/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(blank=True, max_length=200)),
                ("short_description", models.TextField(max_length=500)),
                ("link_text", models.CharField(blank=True, max_length=100)),
                ("link_url", models.URLField(blank=True)),
                ("social_links", models.JSONField(default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_contents",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cards/images/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("link_text", models.CharField(blank=True, max_length=100)),
                ("is_email", models.BooleanField(default=False)),
                ("is_phone", models.BooleanField(default=False)),
                ("auto_fetch_title", models.BooleanField(default=True)),
                ("auto_fetch_description", models.BooleanField(default=True)),
                ("auto_fetch_image", models.BooleanField(default=True)),
                ("fetched_title", models.CharField(blank=True, max_length=200)),
                ("fetched_description", models.TextField(blank=True)),
                ("fetched_image_url", models.URLField(blank=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_contents",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecommendationContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cards/images/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription_text", models.CharField(blank=True, max_length=200)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_contents",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecommendationPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cards/picks/"),
                ),
                ("link_text", models.CharField(blank=True, max_length=100)),
                ("link_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picks",
                        to="cards.recommendationcontent",
                    ),
                ),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
        migrations.CreateModel(
            name="SplashContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cards/images/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(blank=True, max_length=200)),
                ("link_text", models.CharField(blank=True, max_length=100)),
                ("link_url", models.URLField(blank=True)),
                ("social_links", models.JSONField(default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splash_contents",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YouTubeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cards/images/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel_url", models.URLField()),
                ("button_label", models.CharField(default="Subscribe", max_length=50)),
                ("max_videos", models.PositiveIntegerField(default=100)),
                ("auto_fetch_videos", models.BooleanField(default=False)),
                ("last_video_fetch", models.DateTimeField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_contents",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "youtube_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="cards.youtubecontent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-published_at"],
            },
        ),
    ]
